### ISSUE TITLE
500 - Internal Server Error on users permissions page

### ISSUE THREAD

**Issue by Lucqqq** [DouwJacobs/plex-shuffler#107]
Hi there,
I'm running the latest version (1.3.1) of plex-shuffler.
When accessing my users permissions setting at "/profile/settings/permissions" I only get "500 - Internal Server Error".
![image](https://github.com/DouwJacobs/plex-shuffler/assets/108678440/42201462-126e-4fd7-9e5a-54d58d64df29)

Opening the browsers console shows:
```GET https://domain/api/v1/user/1/settings/permissions 404 (Not Found)```

Https is handled by my reverse proxy and shouldn't be the problem since everything else is working just fine.

PS: I love the project and keep up the good work. 👍

**Comment by DouwJacobs** [comment]
Hi @Lucqqq, thanks for raising this. Working on it 😁
