### ISSUE TITLE
Login from behind Reverse Proxy 403 Error

### ISSUE THREAD

**Issue by Healzangels** [DouwJacobs/plex-shuffler#110]
Greetings!
Thanks for sharing such a cool project!
I recently setup running on unRaid via Docker.
Running version 1.3.2

When accessing locally via address:port everything works great. However when trying to access via a reverse proxy subdomain setup as shuffle.mydomain.com I receive a 403 error message within the browser console after attempting to login. 

There I can see the follow address mentioned `https://shuffle.mydomain.com/api/v1/auth/me` which navigating leads to the below.
`{"status":403,"error":"You do not have permission to access this endpoint"}`
![errors](https://github.com/DouwJacobs/plex-shuffler/assets/47136415/c10db35c-1cb6-49c1-8583-67427d95c006)

**Comment by DouwJacobs** [comment]
Hi @Healzangels !

Will you please try deleting cookies for your domain and try again?

**Comment by DouwJacobs** [comment]
Updated cookie name

**Comment by Healzangels** [comment]
Thanks, things seem to be working well now!
