### ISSUE TITLE
Plex Auth Token After Logging in through UI is Invalid

### ISSUE THREAD

**Issue by cheeseandcereal** [DouwJacobs/plex-shuffler#120]
I'm using plex shuffler v1.3.3, when I log in through the UI, the plex shuffler server logs:

```
2024-06-22T02:31:06.752Z [error]: Error checking user access: Request failed with status code 401
```

It's unclear why this is happening since the login in the UI is succeeding. Maybe something with the plex oauth changed so that the shuffler isn't handling it correctly anymore?

**Comment by DouwJacobs** [comment]
Hi @cheeseandcereal

Thanks for creating an issue. It should be fixed in the new docker development image. Will you please test and let me know?

Thanks!

**Comment by cheeseandcereal** [comment]
Yeah, it seems to be working on dev now, thanks!
