### ISSUE TITLE
Allow selection of libraries in settings

### ISSUE THREAD

**Issue by dhicock** [DouwJacobs/plex-shuffler#91]
I have multiple libraries, and it only grabs the first library alphabetically in the type.
As a result, I can only select movies from my 3D Movies library, and from the Anime Shows library. Is there a way to change this behavior? Possibly a dropdown on the plex settings page that allows you to choose the library to pull from?

**Comment by MrPistachios** [comment]
I am having this same issue, all I can select is the random stuff from my DVR library instead of being able to select my Shows library

**Comment by MrPistachios** [comment]
I found if I go to my config folder there is a settings.json, in that I found all my libraries were marked disabled, although DVR still shows up somehow


`"libraries": [
   {
    "id": "1",
    "name": "Movies",
    "enabled": false,
    "type": "movie"
   },
   {
    "id": "4",
    "name": "DVR",
    "enabled": false,
    "type": "show"
   },
   {
    "id": "2",
    "name": "Shows",
    "enabled": false,
    "type": "show"
   },
   {
    "id": "11",
    "name": "YouTube",
    "enabled": false,
    "type": "show"`

**Comment by DouwJacobs** [comment]
I will work on a fix or the option to select a library. Will push it in the upcoming week
